// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jsiwxyffmoktxouniklx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzaXd4eWZmbW9rdHhvdW5pa2x4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODE1NTAsImV4cCI6MjA2Mzg1NzU1MH0.USd8B04xm2XOqyNtR2wQkjzww6WEa-6eers63zmCNmw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);